services:
  power-manager-api:
    build: .
    command: fastapi dev --host 0.0.0.0 ./src/main.py
    # volumes:
    #   - .:/app:ro
    tty: true
    ports:
      - "8000:8000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/"]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
  
  curler:
    image: curlimages/curl:latest
    depends_on:
      power-manager-api:
        condition: service_healthy
    command: ["curl", "-X", "POST", "http://power-manager-api:8000/add_event/", "-H", "Content-Type: application/json", "-d", '{"name":"test event","lat":47.5,"lon":-118.5}']
    tty: true